"""add_model_table_and_relationships

Revision ID: 231981aa7eff
Revises: bdbe1aa5e6c7
Create Date: 2025-03-16 11:59:02.645677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231981aa7eff'
down_revision = 'bdbe1aa5e6c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The models table already exists, so we only need to add the foreign keys
    
    # Add foreign keys to the existing tables
    op.add_column('baseplates', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'baseplates', 'models', ['model_id'], ['id'])
    op.add_column('bins', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bins', 'models', ['model_id'], ['id'])
    op.add_column('generated_files', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_files', 'models', ['model_id'], ['id'])
    
    # Remove the freecad_path column which is no longer needed
    op.drop_column('user_settings', 'freecad_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('freecad_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generated_files', type_='foreignkey')
    op.drop_column('generated_files', 'model_id')
    op.drop_constraint(None, 'bins', type_='foreignkey')
    op.drop_column('bins', 'model_id')
    op.drop_constraint(None, 'baseplates', type_='foreignkey')
    op.drop_column('baseplates', 'model_id')
    # We don't drop the models table since it already existed
    # ### end Alembic commands ###