"""Add bin and baseplate models

Revision ID: 85e507dd8a08
Revises: 
Create Date: 2025-01-23 21:57:09.905160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e507dd8a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bins', 'name')
    # ### end Alembic commands ###